import "./globals.css";

export const metadata = { title: "service", description: "Generated by UDesigner Studio" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
